version: '3.0'

services:
  cat-api-service:
    build: ./cat-api
    volumes:
      - ./cat-api:/usr/src/app
    ports:
      - 8001:6401
  website:
    build: ./website
    volumes:
      - ./website:/usr/src/app
    ports:
      - 8000:6400